### PR TITLE
Simple sidebar

### PR DESCRIPTION
**Pull request by rosasam**
This PR adds a nice little toolbar/sidebar to the crossword, as requested in #18.

image

Features:
- Return home by clicking on title
- Choose tool by clicking it in the sidebar
- Highlight selected tool
- Show keyboard shortcuts for tools
 
Known limitations/TODOs:
- Zooming also zooms the sidebar
- You cannot minimize the sidebar
- Lacks functionality such as help panel and active users

These should be implemented in another PR, just listing the known issues here.

### CODE REVIEW

**Comment by jhnj** [comment]
Would it be possible to add fontawesome as a git submodule instead? Or add it in a separate PR? Currently, this PR is pretty much impossible to review in the github UI at least :)

Looks good, but breaks the writing. The letter and cursor canvases gets moved to the right a bit (can be seen with the html inspector) resulting in the cursor position being wrong. I assume it some css change that causes this.

Also, added a commit changing onkeyup to onkeydown, increases responsiveness. Doesn't really belong to thing PR but didn't want to cause any merge conflicts.

**Comment by jhnj** [comment]
Fixed the css problems with write mode

**Comment by jhnj** [comment]
Made something like this to make the menu be less in the way for people zooming in on smaller screens. See latest commit on branch https://github.com/thesauri/korsord/tree/jhnj/minimize-sidebar. Feel free to cherry-pick that commit and merge it here :)

Peek 2020-04-09 22-46

**Comment by jhnj** [comment]
Also, @rosasam , it seems like some of your commits on this PR are duplicated. Not sure why that is, but no need to fix.

**Comment by rosasam** [comment]
Yeah, I somehow created duplicate commits with rebasing, I think..

**Comment by rosasam** [comment]
I aint got any fancy gifs, but this is the look now:
image

image

**Pull request merged**
